import { Head, usePage } from '@inertiajs/react';
import AdminLayout from '@/Layouts/AdminLayout';
import BigNumber from '@/Components/BigNumber';
import ResponsiveTable from '@/Components/ResponsiveTable';
import Pagination, { PageData } from '@/Components/Pagination';

type Entry={id:number;entry_date:string;description:string;invoice_number:string;classroom?:string;amount_in:number;running_balance:number};
type Props={entries:PageData<Entry>;summary:{total:number;count:number;opening_balance:number;closing_balance:number};filters:Record<string,string|undefined>};
const rupiah=(value:number)=>`Rp ${value.toLocaleString('id-ID')}`;
const dateId=(value:string)=>new Date(value).toLocaleDateString('id-ID',{day:'numeric',month:'short',year:'numeric'});
export default function CashLedger({entries,summary,filters}:Props){const p=usePage().props as {appName?:string;schoolSettings?:Record<string,string>};const rows=entries.data.map(e=>({id:e.id,tanggal:<span className="nowrap">{dateId(e.entry_date)}</span>,keterangan:e.description,tagihan:<span className="nowrap">{e.invoice_number}</span>,kelas:e.classroom??'—',masuk:<span className="money-value">{rupiah(e.amount_in)}</span>,saldo:<span className="money-value">{rupiah(e.running_balance)}</span>}));const query=new URLSearchParams(filters as Record<string,string>).toString();return <AdminLayout appName={p.appName} schoolName={p.schoolSettings?.school_name}><Head title="Buku kas"/><header className="data-heading"><div><p className="eyebrow">Keuangan</p><h1>Buku kas</h1><p>Entri dibuat otomatis saat tagihan berstatus Lunas.</p></div><div className="export-actions"><a className="button-secondary" href={`/admin/buku-kas/excel?${query}`}>Export Excel</a><a className="button-primary" href={`/admin/buku-kas/pdf?${query}`}>Export PDF</a></div></header><section className="ledger-hero tile"><div><BigNumber label="Total masuk">{rupiah(summary.total)}</BigNumber><p>{summary.count} transaksi · Saldo awal {rupiah(summary.opening_balance)}</p></div><form className="date-range"><label className="form-field">Dari<input type="date" name="start_date" defaultValue={filters.start_date}/></label><label className="form-field">Sampai<input type="date" name="end_date" defaultValue={filters.end_date}/></label><button className="button-secondary">Terapkan</button></form></section><section className="data-panel ledger-list"><ResponsiveTable rows={rows} columns={[{key:'tanggal',label:'Tanggal'},{key:'keterangan',label:'Keterangan'},{key:'tagihan',label:'No. tagihan'},{key:'kelas',label:'Kelas'},{key:'masuk',label:'Masuk'},{key:'saldo',label:'Saldo berjalan'}]}/><div className="ledger-total"><strong>Total penerimaan periode ini</strong><strong>{rupiah(summary.total)}</strong><strong>{rupiah(summary.closing_balance)}</strong></div><Pagination page={entries}/></section></AdminLayout>}
