import { Head, Link, router, useForm, usePage } from '@inertiajs/react';
import { useState } from 'react';
import AdminLayout from '@/Layouts/AdminLayout';
import Tile from '@/Components/Tile';
import BigNumber from '@/Components/BigNumber';
import StatusCapsule from '@/Components/StatusCapsule';
import ResponsiveTable from '@/Components/ResponsiveTable';
import ConfirmDialog from '@/Components/ConfirmDialog';
import Pagination, { PageData } from '@/Components/Pagination';
import LoadingState from '@/Components/LoadingState';

type Invoice = { id:number; invoice_number:string; student:string; nis:string; classroom:string|null; month:number; year:number; amount:number; discount_amount:number; net_amount:number; due_date:string; status:string; overdue_days:number };
type Props = { invoices:PageData<Invoice>; academicYears:{id:number;name:string;is_active:boolean}[]; classrooms:{id:number;name:string;academic_year_id:number}[]; filters:Record<string,string|number|undefined>; currentPeriod:{month:number;year:number} };
const months = ['Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember'];
const rupiah = (value:number) => `Rp ${value.toLocaleString('id-ID')}`;
const dateId = (value:string) => new Date(value).toLocaleDateString('id-ID', { day:'numeric', month:'short', year:'numeric' });
export default function Invoices({ invoices, academicYears, classrooms, filters, currentPeriod }:Props) {
    const page = usePage().props as { appName?:string; schoolSettings?:Record<string,string>; flash?:{success?:string} };
    const activeYear = academicYears.find(y => y.is_active) ?? academicYears[0];
    const [generateOpen,setGenerateOpen] = useState(false); const [preview,setPreview] = useState<{created:number;skipped:number}|null>(null); const [previewing,setPreviewing] = useState(false);
    const [form,setForm] = useState({month:String(filters.month ?? currentPeriod.month), year:String(filters.year ?? currentPeriod.year), academic_year_id:String(filters.academic_year_id ?? activeYear?.id ?? ''), amount:String(filters.amount ?? page.schoolSettings?.default_spp_amount ?? ''), due_date:String(filters.due_date ?? `${currentPeriod.year}-${String(currentPeriod.month).padStart(2,'0')}-10`) });
    const change = (key:string,value:string) => setForm(current => ({...current,[key]:value}));
    const apply = (event:React.FormEvent) => { event.preventDefault(); router.get('/admin/tagihan',{...filters,...form, month:form.month, year:form.year, academic_year_id:form.academic_year_id},{preserveState:true,replace:true}); };
    const openGenerate = async () => { setPreviewing(true); try { const response=await fetch('/admin/tagihan/preview',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name=csrf-token]')?.getAttribute('content') ?? ''},body:JSON.stringify(form)}); if(response.ok) { setPreview(await response.json()); setGenerateOpen(true); } } finally { setPreviewing(false); } };
    const submitGenerate = () => router.post('/admin/tagihan/generate',form,{onSuccess:()=>setGenerateOpen(false)});
    const rows = invoices.data.map(invoice => ({ id:invoice.id, siswa:<div className="row-title">{invoice.student}<span>{invoice.nis}</span></div>, kelas:invoice.classroom ?? 'Belum ditempatkan', periode:`${months[invoice.month-1]} ${invoice.year}`, nominal:<span className="money-value">{rupiah(invoice.net_amount)}</span>, jatuh_tempo:<span className="date-stack">{dateId(invoice.due_date)}{invoice.overdue_days>0&&<small>terlambat {invoice.overdue_days} hari</small>}</span>, status:<StatusCapsule status={invoice.status}/>, aksi:invoice.status==='lunas'?<span className="caption">Final</span>:<button className="button-secondary" onClick={()=>{const value=window.prompt('Nominal akhir',String(invoice.net_amount)); if(value) router.patch(`/admin/tagihan/${invoice.id}/nominal`,{net_amount:Number(value)},{preserveScroll:true});}}>Ubah nominal</button> }));
    return <AdminLayout appName={page.appName} schoolName={page.schoolSettings?.school_name}><Head title="Tagihan SPP" />
        <header className="data-heading"><div><p className="eyebrow">Keuangan</p><h1>Tagihan SPP</h1><p>{invoices.total} data tagihan tercatat</p></div><nav className="master-tabs"><Link className="is-active" href="/admin/tagihan">Tagihan</Link><Link href="/admin/verifikasi">Verifikasi</Link><Link href="/admin/buku-kas">Buku kas</Link></nav></header>
        {page.flash?.success&&<p className="notice" role="status">{page.flash.success}</p>}
        <Tile title="Generate tagihan bulanan" className="invoice-generator"><p>Buat tagihan SPP rutin untuk seluruh siswa aktif pada tahun ajaran terpilih.</p><form className="invoice-generator-grid" onSubmit={apply}><label className="form-field">Bulan<select value={form.month} onChange={e=>change('month',e.target.value)}>{months.map((month,i)=><option key={month} value={i+1}>{month}</option>)}</select></label><label className="form-field">Tahun ajaran<select value={form.academic_year_id} onChange={e=>change('academic_year_id',e.target.value)}>{academicYears.map(year=><option key={year.id} value={year.id}>{year.name}</option>)}</select></label><label className="form-field">Nominal SPP<input type="number" min="0" value={form.amount} onChange={e=>change('amount',e.target.value)} /></label><label className="form-field">Jatuh tempo<input type="date" value={form.due_date} onChange={e=>change('due_date',e.target.value)} /></label><button className="button-primary" type="button" onClick={openGenerate} disabled={previewing}>{previewing?'Menghitung…':'Generate untuk semua siswa aktif'}</button></form></Tile>
        <section className="data-panel invoice-list"><div className="filter-bar"><form className="invoice-filters" onSubmit={apply}><label className="form-field">Bulan<select name="month" value={String(filters.month??'')} onChange={e=>change('month',e.target.value)}><option value="">Semua bulan</option>{months.map((month,i)=><option key={month} value={i+1}>{month}</option>)}</select></label><label className="form-field">Kelas<select value={String(filters.classroom_id??'')} onChange={e=>router.get('/admin/tagihan',{...filters,classroom_id:e.target.value},{preserveState:true,replace:true})}><option value="">Semua kelas</option>{classrooms.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="form-field">Status<select value={String(filters.status??'')} onChange={e=>router.get('/admin/tagihan',{...filters,status:e.target.value},{preserveState:true,replace:true})}><option value="">Semua status</option><option value="lunas">Lunas</option><option value="menunggu_verifikasi">Menunggu verifikasi</option><option value="belum_bayar">Belum bayar</option><option value="ditolak">Ditolak</option></select></label><button className="button-secondary">Terapkan</button></form></div><ResponsiveTable rows={rows} columns={[{key:'siswa',label:'Siswa'},{key:'kelas',label:'Kelas'},{key:'periode',label:'Bulan'},{key:'nominal',label:'Nominal'},{key:'jatuh_tempo',label:'Jatuh tempo'},{key:'status',label:'Status'},{key:'aksi',label:'Aksi'}]}/><Pagination page={invoices}/></section>
        <ConfirmDialog open={generateOpen} title={`${preview?.created ?? 0} tagihan akan dibuat`} description={`Tagihan ${months[Number(form.month)-1]} ${form.year}. ${preview?.skipped ?? 0} siswa dilewati karena sudah memiliki tagihan periode ini.`} confirmLabel="Generate" onCancel={()=>setGenerateOpen(false)} onConfirm={submitGenerate}/>
    </AdminLayout>;
}
