import { Head, Link, router, useForm, usePage } from '@inertiajs/react';
import { useState } from 'react';
import AdminLayout from '@/Layouts/AdminLayout';
import StatusCapsule from '@/Components/StatusCapsule';
import ProgressSteps from '@/Components/ProgressSteps';
import BottomSheet from '@/Components/BottomSheet';
import EmptyState from '@/Components/EmptyState';
import Pagination, { PageData } from '@/Components/Pagination';

type QueuePayment={id:number;student:string;month:number;year:number;invoice_amount:number;submitted_at:string};
type Detail=QueuePayment & {invoice_number:string;nis:string;classroom?:string;guardian:string;amount_transferred:number;transfer_date:string;sender_name:string;note?:string;proof_url:string;proof_type:string};
const monthName=(month:number)=>new Date(2000,month-1,1).toLocaleDateString('id-ID',{month:'long'});
const rupiah=(value:number)=>`Rp ${value.toLocaleString('id-ID')}`;
export default function PaymentVerification({payments,selected,detailOpen}:{payments:PageData<QueuePayment>;selected:Detail|null;detailOpen:boolean}) {
 const p=usePage().props as {appName?:string;schoolSettings?:Record<string,string>;flash?:{success?:string}}; const [rejectOpen,setRejectOpen]=useState(false); const rejection=useForm({rejection_reason:''});
 const review=(action:'setujui'|'tolak')=>{if(!selected)return; if(action==='setujui') router.post(`/admin/verifikasi/${selected.id}/setujui`,{}, {preserveScroll:true}); else setRejectOpen(true);};
 const submitReject=()=>{if(!selected)return; rejection.post(`/admin/verifikasi/${selected.id}/tolak`,{onSuccess:()=>setRejectOpen(false)});};
 return <AdminLayout appName={p.appName} schoolName={p.schoolSettings?.school_name}><Head title="Verifikasi pembayaran"/><header className="data-heading payment-heading"><div><p className="eyebrow">Keuangan</p><h1>Verifikasi pembayaran</h1><p>{payments.total} pembayaran menunggu</p></div><Link href="/admin/tagihan" className="button-secondary">Tagihan SPP</Link></header>{p.flash?.success&&<p className="notice" role="status">{p.flash.success}</p>}
 <div className="verification-layout"><section className="payment-queue"><div className="queue-heading"><h2>Antrean pembayaran</h2><span>{payments.total} menunggu</span></div>{payments.data.length===0?<EmptyState>Tidak ada pembayaran yang menunggu.</EmptyState>:<>{payments.data.map(payment=><Link key={payment.id} href={`/admin/verifikasi?payment=${payment.id}`} className={`payment-queue-row ${selected?.id===payment.id?'is-selected':''}`}><strong>{payment.student}</strong><span>{monthName(payment.month)} {payment.year} · {rupiah(payment.invoice_amount)}</span><small>{payment.submitted_at}</small></Link>)}<Pagination page={payments}/></>}</section>{selected?<section className="payment-detail"><div className="payment-detail-header"><div><h2>{selected.student}</h2><p>NIS {selected.nis} · {selected.classroom ?? 'Belum ada kelas'}</p></div><StatusCapsule status="menunggu_verifikasi"/></div><div className="payment-detail-grid"><div><h3>Bukti bayar</h3><div className="proof-preview">{selected.proof_type==='image'?<img src={selected.proof_url} alt="Bukti transfer"/>:<iframe src={selected.proof_url} title="Bukti transfer PDF"/>}</div><a className="parent-detail-link" href={selected.proof_url} target="_blank" rel="noreferrer">Buka ukuran penuh ↗</a></div><div className="payment-facts"><h3>Rincian transaksi</h3><dl><div><dt>Orang tua</dt><dd>{selected.guardian}</dd></div><div><dt>Tagihan</dt><dd>{selected.invoice_number}</dd></div><div><dt>Nominal tagihan</dt><dd>{rupiah(selected.invoice_amount)}</dd></div><div><dt>Nominal transfer</dt><dd>{rupiah(selected.amount_transferred)} <StatusCapsule status={selected.amount_transferred===selected.invoice_amount?'lunas':'ditolak'} label={selected.amount_transferred===selected.invoice_amount?'Sesuai':`Selisih ${rupiah(Math.abs(selected.amount_transferred-selected.invoice_amount))}`}/></dd></div><div><dt>Tanggal transfer</dt><dd>{new Date(selected.transfer_date).toLocaleDateString('id-ID',{day:'numeric',month:'short',year:'numeric'})}</dd></div><div><dt>Nama pengirim</dt><dd>{selected.sender_name}</dd></div>{selected.note&&<div><dt>Catatan</dt><dd>{selected.note}</dd></div>}</dl><ProgressSteps steps={['Belum bayar','Menunggu verifikasi','Lunas']} current={1}/><div className="payment-actions"><button className="button-primary" onClick={()=>review('setujui')}>Setujui (tandai lunas)</button><button className="button-danger" onClick={()=>review('tolak')}>Tolak</button></div></div></div></section>:<section className="payment-detail empty-detail"><EmptyState>Pilih pembayaran dari antrean.</EmptyState></section>}</div>
 <BottomSheet open={rejectOpen} title="Tolak pembayaran" onClose={()=>setRejectOpen(false)}><div className="reject-form"><p>Alasan penolakan wajib diisi agar orang tua dapat memperbaiki bukti.</p><textarea aria-label="Alasan penolakan" value={rejection.data.rejection_reason} onChange={e=>rejection.setData('rejection_reason',e.target.value)} placeholder="Tulis alasan penolakan"/><div className="quick-reasons">{['Nominal tidak sesuai','Bukti tidak terbaca','Bukan bukti transfer SPP'].map(reason=><button type="button" key={reason} onClick={()=>rejection.setData('rejection_reason',reason)}>{reason}</button>)}</div>{rejection.errors.rejection_reason&&<p className="field-error">{rejection.errors.rejection_reason}</p>}<button type="button" className="button-danger" disabled={rejection.processing} onClick={submitReject}>Tolak pembayaran</button></div></BottomSheet></AdminLayout>;
}
